#!/bin/bash
# Run on uw1-web02 (us-west-1) as root.
# Accepts TRAFFIC_SIM_* vars via 'sudo env KEY=val bash ...' (healthcare-deploy.sh pattern),
# or falls back to sourcing ../config.env for manual runs on the node.
set -euo pipefail

# ── Config resolution ─────────────────────────────────────────
# When called via healthcare-deploy.sh the vars are already in the environment.
# When run manually on the node, source config.env as a fallback.
if [[ -z "${TRAFFIC_SIM_SERVER_HOST:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    CONFIG_ENV="$SCRIPT_DIR/../config.env"
    if [[ -f "$CONFIG_ENV" ]]; then
        # shellcheck source=../config.env
        source "$CONFIG_ENV"
    else
        echo "ERROR: TRAFFIC_SIM_SERVER_HOST not set and config.env not found at $CONFIG_ENV" >&2
        exit 1
    fi
fi

SERVER_HOST="${TRAFFIC_SIM_SERVER_HOST}"
SERVER_PORT="${TRAFFIC_SIM_PORT:-873}"
DURATION="${TRAFFIC_SIM_DURATION_SECONDS:-1200}"
SCHEDULE_DAYS="${TRAFFIC_SIM_SCHEDULE_DAYS:-1,3}"
START_HOUR_UTC="${TRAFFIC_SIM_START_HOUR_UTC:-13}"
RANDOM_WINDOW="${TRAFFIC_SIM_RANDOM_WINDOW_S:-31200}"
ENABLED="${TRAFFIC_SIM_ENABLED:-true}"

CLIENT_DIR="/opt/replication-client"
SERVICE_FILE="/etc/systemd/system/replication-traffic.service"
CONF_FILE="/etc/replication-client.conf"
CRON_FILE="/etc/cron.d/replication-traffic"

echo "==> Config: server=${SERVER_HOST}:${SERVER_PORT}, duration=${DURATION}s, enabled=${ENABLED}"
echo "    Schedule: days=${SCHEDULE_DAYS}, fire=${START_HOUR_UTC}:00 UTC, max-delay=${RANDOM_WINDOW}s"

echo "==> Installing client script"
mkdir -p "$CLIENT_DIR"
SCRIPT_SRC="${BASH_SOURCE[0]%/*}/run-traffic.sh"
[[ -f "$SCRIPT_SRC" ]] || SCRIPT_SRC="$(cd "$(dirname "$0")" && pwd)/run-traffic.sh"
cp "$SCRIPT_SRC" "$CLIENT_DIR/run-traffic.sh"
chmod 755 "$CLIENT_DIR/run-traffic.sh"

echo "==> Writing environment config ($CONF_FILE)"
cat > "$CONF_FILE" <<EOF
# Replication traffic client config — regenerated by client-setup.sh.
# Edit deploy/config.env (TRAFFIC_SIM_*) and re-run healthcare-deploy.sh init traffic-sim.
REPLICATION_SERVER_HOST=${SERVER_HOST}
REPLICATION_SERVER_PORT=${SERVER_PORT}
REPLICATION_DURATION_SECONDS=${DURATION}
EOF
chmod 640 "$CONF_FILE"

echo "==> Installing systemd service"
SERVICE_SRC="${BASH_SOURCE[0]%/*}/replication-traffic.service"
[[ -f "$SERVICE_SRC" ]] || SERVICE_SRC="$(cd "$(dirname "$0")" && pwd)/replication-traffic.service"
cp "$SERVICE_SRC" "$SERVICE_FILE"
systemctl daemon-reload
systemctl disable replication-traffic.service 2>/dev/null || true

if [[ "$ENABLED" == "true" ]]; then
    echo "==> Installing cron job (TRAFFIC_SIM_ENABLED=true)"
    cat > "$CRON_FILE" <<EOF
# Replication traffic simulation — config.env TRAFFIC_SIM_*
# Fires at ${START_HOUR_UTC}:00 UTC on days ${SCHEDULE_DAYS} (Mon=1, Wed=3).
# Random delay up to ${RANDOM_WINDOW}s ($(( RANDOM_WINDOW / 3600 ))h$(( (RANDOM_WINDOW % 3600) / 60 ))m) before starting the ${DURATION}s burst.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

0 ${START_HOUR_UTC} * * ${SCHEDULE_DAYS} root \\
    DELAY=\$(shuf -i 0-${RANDOM_WINDOW} -n 1 2>/dev/null || echo \$((RANDOM * RANDOM % ${RANDOM_WINDOW}))); \\
    sleep "\$DELAY"; \\
    systemctl start replication-traffic.service
EOF
    chmod 644 "$CRON_FILE"
    echo "    Cron installed: /etc/cron.d/replication-traffic"
else
    echo "==> Skipping cron (TRAFFIC_SIM_ENABLED=false)"
    rm -f "$CRON_FILE"
fi

echo ""
echo "==> Client installed."
echo "    Server : ${SERVER_HOST}:${SERVER_PORT}"
echo "    Logs   : journalctl -u replication-traffic -f"
echo ""
echo "    Manual test (runs immediately, no random delay):"
echo "    systemctl start replication-traffic.service"
