#!/bin/bash
# ============================================================
# CareConnect EHR — Splunk OTel Collector Setup
# Run this script on ALL THREE VMs after the main setup scripts.
#
# Usage:
#   sudo bash 05-setup-otel-collector.sh frontend   (VM1)
#   sudo bash 05-setup-otel-collector.sh api        (VM2)
#   sudo bash 05-setup-otel-collector.sh db         (VM3)
# ============================================================
set -euo pipefail

# ── CONFIGURATION ──────────────────────────────────────────
# Splunk Observability Cloud — APM traces and infrastructure metrics
SPLUNK_ACCESS_TOKEN="${SPLUNK_ACCESS_TOKEN:-CHANGE_THIS_O11Y_ACCESS_TOKEN}"  # Ingest token
SPLUNK_REALM="${SPLUNK_REALM:-us1}"                                           # us0, us1, eu0, ap0, etc.
APP_ENV="${APP_ENV:-production}"

# Splunk Platform (internal instance) — logs
SPLUNK_PLATFORM_HEC_URL="${SPLUNK_PLATFORM_HEC_URL:-https://splunk.internal.example.com:8088/services/collector/event}"
SPLUNK_PLATFORM_HEC_TOKEN="${SPLUNK_PLATFORM_HEC_TOKEN:-CHANGE_THIS_PLATFORM_HEC_TOKEN}"

# For VM3 (database) only — PostgreSQL credentials for metrics
DB_USER="${DB_USER:-careconnect}"
DB_PASSWORD="${DB_PASSWORD:-CHANGE_THIS_STRONG_PASSWORD}"  # Match 01-setup-db.sh

# ── For VM2 (API): also update the API .env with collector endpoint
# The Node.js app sends traces to the local collector instead of
# directly to Splunk, so set this on VM2 after running this script:
#   echo "OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317" >> /opt/careconnect/api/.env
# ───────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓ $1${NC}"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠ $1${NC}"; }
err()  { echo -e "${RED}[$(date '+%H:%M:%S')] ✗ $1${NC}"; exit 1; }
info() { echo -e "${BLUE}[$(date '+%H:%M:%S')] → $1${NC}"; }

ROLE="${1:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash 05-setup-otel-collector.sh [frontend|api|db]"
[[ -z "$ROLE" ]] && err "Specify role: frontend, api, or db"
[[ "$SPLUNK_ACCESS_TOKEN" == "CHANGE_THIS_O11Y_ACCESS_TOKEN" ]] && \
  err "Set SPLUNK_ACCESS_TOKEN before running"
[[ "$SPLUNK_PLATFORM_HEC_TOKEN" == "CHANGE_THIS_PLATFORM_HEC_TOKEN" ]] && \
  err "Set SPLUNK_PLATFORM_HEC_TOKEN before running"

info "Setting up Splunk OTel Collector on ${ROLE} VM..."

# ── Install Splunk OTel Collector ─────────────────────────────
if systemctl is-active --quiet splunk-otel-collector 2>/dev/null; then
  warn "Collector already installed — will reconfigure"
else
  info "Downloading and installing Splunk OTel Collector..."

  # Official Splunk install script — installs as systemd service
  curl -sSfL https://dl.signalfx.com/splunk-otel-collector.sh -o /tmp/splunk-otel-collector.sh

  # Install without starting (we'll write our own config first)
  SPLUNK_ACCESS_TOKEN="${SPLUNK_ACCESS_TOKEN}" \
  SPLUNK_REALM="${SPLUNK_REALM}" \
    sh /tmp/splunk-otel-collector.sh \
    --realm "${SPLUNK_REALM}" \
    --memory 512 \
    --mode agent \
    --without-instrumentation

  rm -f /tmp/splunk-otel-collector.sh
  log "Splunk OTel Collector installed"
fi

# ── Write collector configuration ─────────────────────────────
CONFIG_DIR="/etc/otel/collector"
mkdir -p "${CONFIG_DIR}"

info "Writing ${ROLE} collector configuration..."
cp "${SCRIPT_DIR}/configs/otel-collector-${ROLE}.yaml" \
   "${CONFIG_DIR}/agent_config.yaml"
log "Config written to ${CONFIG_DIR}/agent_config.yaml"

# ── Write environment file for the collector ─────────────────
info "Writing collector environment file..."
ENV_FILE="/etc/otel/collector/splunk-otel-collector.conf"

cat > "${ENV_FILE}" <<EOF
# Splunk OTel Collector environment — auto-generated by 05-setup-otel-collector.sh
# APM traces + infrastructure metrics → Splunk Observability Cloud
SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
SPLUNK_REALM=${SPLUNK_REALM}
SPLUNK_MEMORY_TOTAL_MIB=512
APP_ENV=${APP_ENV}
# Logs → internal Splunk Platform instance
SPLUNK_PLATFORM_HEC_URL=${SPLUNK_PLATFORM_HEC_URL}
SPLUNK_PLATFORM_HEC_TOKEN=${SPLUNK_PLATFORM_HEC_TOKEN}
EOF

# Add DB credentials for the database VM
if [[ "$ROLE" == "db" ]]; then
  cat >> "${ENV_FILE}" <<EOF
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF
fi

chmod 600 "${ENV_FILE}"
log "Environment file written (${ENV_FILE})"

# ── Configure OTLP endpoint for API VM (Node.js → Collector) ──
if [[ "$ROLE" == "api" ]]; then
  info "Configuring Node.js app to send traces to local collector..."
  API_ENV="/opt/careconnect/api/.env"

  if [[ -f "${API_ENV}" ]]; then
    # Remove any existing OTLP endpoint setting and add new one
    sed -i '/OTEL_EXPORTER_OTLP/d' "${API_ENV}"
    sed -i '/SPLUNK_ACCESS_TOKEN/d' "${API_ENV}"
    sed -i '/SPLUNK_REALM/d' "${API_ENV}"

    cat >> "${API_ENV}" <<EOF

# Splunk APM — send traces to local collector (avoids per-node token management)
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
OTEL_SERVICE_NAME=careconnect-api
OTEL_RESOURCE_ATTRIBUTES=deployment.environment=${APP_ENV}
EOF
    log "API .env updated with OTLP collector endpoint"

    # Reload PM2 to pick up new env vars
    if command -v pm2 &>/dev/null; then
      sudo -u careconnect pm2 reload careconnect-api --update-env 2>/dev/null && \
        log "PM2 reloaded with new environment" || \
        warn "PM2 reload failed — restart manually: sudo -u careconnect pm2 restart careconnect-api"
    fi
  else
    warn "${API_ENV} not found — run 02-setup-api.sh first"
  fi

  # Open OTLP port 4317/4318 to the app (localhost only — already restricted)
  ufw allow from 127.0.0.1 to any port 4317 comment 'OTLP gRPC - localhost only' 2>/dev/null || true
  ufw allow from 127.0.0.1 to any port 4318 comment 'OTLP HTTP - localhost only' 2>/dev/null || true
fi

# ── Start / restart collector ─────────────────────────────────
info "Starting Splunk OTel Collector..."
systemctl daemon-reload
systemctl enable splunk-otel-collector
systemctl restart splunk-otel-collector
sleep 3

if systemctl is-active --quiet splunk-otel-collector; then
  log "Splunk OTel Collector running"
else
  warn "Collector may not be running — check: journalctl -u splunk-otel-collector -n 50"
fi

# ── Verify collector health check ─────────────────────────────
sleep 2
HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:13133/ 2>/dev/null || echo "000")
if [[ "$HEALTH" == "200" ]]; then
  log "Collector health check passed"
else
  warn "Collector health check returned ${HEALTH} — may still be starting"
fi

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✓ Splunk OTel Collector setup complete! (${ROLE})${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Config:   ${CONFIG_DIR}/agent_config.yaml"
echo "  Env file: ${ENV_FILE}"
echo "  Status:   systemctl status splunk-otel-collector"
echo "  Logs:     journalctl -u splunk-otel-collector -f"
echo "  Health:   curl http://localhost:13133/"
echo ""

case "$ROLE" in
  api)
    echo "  ── API VM additional info ──────────────────────────────"
    echo "  OTLP gRPC:   localhost:4317  ← Node.js sends traces here"
    echo "  OTLP HTTP:   localhost:4318  ← alternative endpoint"
    echo "  zPages:      http://localhost:55679  ← debug collector"
    ;;
  frontend)
    echo "  ── Frontend VM: Splunk RUM ─────────────────────────────"
    echo "  RUM token and realm are baked into the React build."
    echo "  Re-run 03-setup-frontend.sh with VITE_SPLUNK_RUM_TOKEN"
    echo "  set to your Splunk O11y RUM ingest token."
    ;;
  db)
    echo "  ── DB VM: PostgreSQL metrics ───────────────────────────"
    echo "  PostgreSQL metrics appear in Splunk Infrastructure"
    echo "  Monitoring under the 'careconnect-db' service."
    ;;
esac
echo ""
